version: '3.8'

services:
  web:
    image: nguyentandung2004/innolabs_test_oauth2:1.0.0        
    ports:
      - "8080:8080"          
    depends_on:
      - db                    
    environment:
      - DB_HOST=db            
      - DB_PORT=3306          
      - DB_NAME=innolabs_oauth       
      - DB_USERNAME=root       
      - DB_PASSWORD=12345     
    networks:
      - innolabs_network

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345 
      - MYSQL_DATABASE=innolabs_oauth  
    ports:
      - "3307:3306"    
    volumes:
      - mysql-data:/var/lib/mysql  # Volume để lưu trữ dữ liệu MySQL
      - ./sql/sql.sql:/docker-entrypoint-initdb.d/sql.sql  # Mount file SQL trực tiếp vào container
    networks:
      - innolabs_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:

networks:
  innolabs_network:
    driver: bridge
