version: '3.9' # Sử dụng phiên bản 3.9 để hỗ trợ `condition: service_healthy`

services:
  web:
    image: nguyentandung2004/innolabs_test_oauth2:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Đợi cho đến khi MySQL trở thành "healthy"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=innolabs_oauth
      - DB_USERNAME=root
      - DB_PASSWORD=12345
    networks:
      - innolabs_network

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=innolabs_oauth
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    networks:
      - innolabs_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s # Khoảng thời gian giữa các lần kiểm tra
      timeout: 5s   # Thời gian chờ cho một lần kiểm tra
      retries: 3    # Số lần thử lại trước khi đánh dấu là "unhealthy"

volumes:
  mysql-data:

networks:
  innolabs_network:
    driver: bridge
